"use strict";
const JOBS=["수호성","검성","살성","궁성","정령성","마도성","권성","호법성","치유성"];
const POINTS=["12시","11시","9시","7시","6시","5시","3시","2시"];
const D1P1=["","9 → 12","9","3 → 3","3"], D1P2=["","12 → 9","6 → 6","12","6"];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const emptyChar=()=>({Nickname:"",Server:"",Job:"",Namtool:null});
const emptyRound=()=>({PartyPlayerIds:Array(10).fill(0),PartyCharacterIds:Array(10).fill(""),PartySwapModes:Array(10).fill("고정"),PartySwapCharacterIds:Array(10).fill(""),D1Roles:Array(10).fill(""),Signals:Array(8).fill(""),Mercy:Array(10).fill(""),BackSkull:""});
let state={Version:3,SavedAt:"",PlayerGroups:Array.from({length:10},(_,i)=>({PlayerId:i+1,PlayerName:"",Main:emptyChar(),Sub1:emptyChar(),Sub2:emptyChar(),Sub3:emptyChar(),Sub4:emptyChar(),Sub1ServerOverride:false,Sub2ServerOverride:false,Sub3ServerOverride:false,Sub4ServerOverride:false})),Mercenaries:Array.from({length:10},(_,i)=>({Id:1001+i,MainNickname:"",Nickname:"",Server:"",Job:"",Namtool:null})),Rounds:Array.from({length:5},emptyRound)};
let page=0, mechanicView=false, selectedFormation=new Set();

function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function fmtNam(v){if(v===null||v===undefined||v==="")return ""; let s=String(v).trim().replace(/k$/i,""); return /^\d+$/.test(s)?s+"k":""}
function chars(p){return [p.Main,p.Sub1,p.Sub2,p.Sub3,p.Sub4]}
function typeAt(i){return i===0?"main":"sub"+i}
function full(c){return c&&!(!c.Nickname)?c.Nickname+(c.Server?`[${c.Server}]`:"[]"):""}
function formDisplay(c){let x=full(c);return c&&c.Namtool!=null?x+" "+c.Namtool+"k":x}
function mechDisplay(c){if(!c)return "";return `${c.Type==="main"?"본":"부"}•${full(c)}${c.Job?" "+c.Job:""}${c.Namtool!=null?" "+c.Namtool+"k":""}`}
function playerChoices(){
  let out=state.PlayerGroups.filter(p=>p.PlayerName.trim()).map(p=>({id:p.PlayerId,name:p.PlayerName.trim()}));
  let seen=new Set();
  for(const m of state.Mercenaries){let n=m.MainNickname.trim().toLowerCase();if(n&&!seen.has(n)){seen.add(n);out.push({id:m.Id,name:m.MainNickname.trim()})}}
  return out;
}
function charsForPlayer(id){
  if(id>=1&&id<=10){let p=state.PlayerGroups[id-1];return chars(p).map((c,i)=>({...c,PlayerId:id,CharacterId:`player${id}_${typeAt(i)}`,Type:i===0?"main":"sub",Mercenary:false})).filter(c=>c.Nickname.trim())}
  let leader=state.Mercenaries.find(m=>m.Id===id); if(!leader)return [];
  let main=leader.MainNickname.trim();
  return state.Mercenaries.filter(m=>m.MainNickname.trim().toLowerCase()===main.toLowerCase()&&m.Nickname.trim()).map(m=>({...m,PlayerId:id,CharacterId:`mercenary${m.Id-1000}`,Type:m.MainNickname.trim()===m.Nickname.trim()?"main":"sub",Mercenary:true}));
}
function effective(r,i,boss2=true){let id=r.PartyPlayerIds[i], cid=boss2&&r.PartySwapModes[i]==="교체"?r.PartySwapCharacterIds[i]:r.PartyCharacterIds[i];return charsForPlayer(id).find(c=>c.CharacterId===cid)||null}
function usedBefore(id,round){let s=new Set();for(let r=0;r<round;r++){for(let i=0;i<10;i++)if(state.Rounds[r].PartyPlayerIds[i]===id){let c=effective(state.Rounds[r],i,true);if(c&&!(id<=10&&c.Type==="main"))s.add(c.CharacterId)}}return s}
function available(id,round){let u=usedBefore(id,round);return charsForPlayer(id).filter(c=>!u.has(c.CharacterId))}
function forceSwap(id,round,cid){if(!(id>=1&&id<=10)||!cid.endsWith("_main"))return false;for(let r=0;r<round;r++)for(let i=0;i<10;i++){let pr=state.Rounds[r];if(pr.PartyPlayerIds[i]===id&&pr.PartyCharacterIds[i]===`player${id}_main`&&pr.PartySwapModes[i]==="고정")return true}return false}
function normalizeRound(round){
  let r=state.Rounds[round];
  for(let i=0;i<10;i++){let id=r.PartyPlayerIds[i];if(!playerChoices().some(p=>p.id===id)){r.PartyPlayerIds[i]=0;r.PartyCharacterIds[i]="";r.PartySwapCharacterIds[i]="";r.PartySwapModes[i]="고정";continue}
    let av=available(id,round); if(!av.some(c=>c.CharacterId===r.PartyCharacterIds[i]))r.PartyCharacterIds[i]="";
    let forced=r.PartyCharacterIds[i]&&forceSwap(id,round,r.PartyCharacterIds[i]); if(forced)r.PartySwapModes[i]="교체";
    if(r.PartySwapModes[i]!=="교체")r.PartySwapCharacterIds[i]=""; else if(!av.some(c=>c.CharacterId===r.PartySwapCharacterIds[i])||r.PartySwapCharacterIds[i]===r.PartyCharacterIds[i])r.PartySwapCharacterIds[i]="";
  }
}
function slotComplete(round,i){let r=state.Rounds[round],id=r.PartyPlayerIds[i],base=available(id,round).find(c=>c.CharacterId===r.PartyCharacterIds[i]);if(!id||!base)return false;if(r.PartyPlayerIds.filter(x=>x===id).length>1)return false;if(r.PartySwapModes[i]==="교체")return !!available(id,round).find(c=>c.CharacterId===r.PartySwapCharacterIds[i]&&c.CharacterId!==base.CharacterId);return !forceSwap(id,round,r.PartyCharacterIds[i])}
function complete(round){return Array.from({length:10},(_,i)=>slotComplete(round,i)).every(Boolean)}

function nav(){let n=$("#nav");n.innerHTML=["플레이어 정보","1판","2판","3판","4판","5판"].map((x,i)=>`<button data-p="${i}" class="${page===i?"active ":""}${i===0?"roster":"round"}">${x}</button>`).join("");$$("button",n).forEach(b=>b.onclick=()=>{page=+b.dataset.p;mechanicView=false;selectedFormation.clear();render()})}
function render(){nav();$("#app").innerHTML=""; if(page===0)renderRoster();else renderRound(page-1)}
function inputCell(value,attr=""){return `<input ${attr} value="${esc(value||"")}">`}
function jobSelect(value,attr=""){return `<select ${attr}><option></option>${JOBS.map(j=>`<option ${j===value?"selected":""}>${j}</option>`).join("")}</select>`}
function renderRoster(){
 let app=$("#app");app.innerHTML=`<div class="section-title">고정 플레이어</div><div class="roster-grid" id="rosterGrid"></div><div class="mercs"><div class="section-title">용병</div><div class="merc-grid"><div id="m1"></div><div id="m2"></div></div></div>`;
 let rg=$("#rosterGrid");
 state.PlayerGroups.forEach((p,pi)=>{let card=document.createElement("div");card.className="card";card.innerHTML=`<input class="player-name" placeholder="플레이어 이름" value="${esc(p.PlayerName)}"><table><thead><tr><th>구분</th><th>닉네임</th><th>서버명</th><th>직업</th><th>남툴</th></tr></thead><tbody>${["Main","Sub1","Sub2","Sub3","Sub4"].map((k,i)=>`<tr data-k="${k}"><td>${i===0?"본캐":"부캐"+i}</td><td>${inputCell(p[k].Nickname,'data-f="Nickname"')}</td><td>${inputCell(p[k].Server,'data-f="Server"')}</td><td>${jobSelect(p[k].Job,'data-f="Job"')}</td><td>${inputCell(fmtNam(p[k].Namtool),'data-f="Namtool"')}</td></tr>`).join("")}</tbody></table>`;rg.appendChild(card);
   $(".player-name",card).oninput=e=>{p.PlayerName=e.target.value; if(!p.Main.Nickname.trim()&&p.PlayerName.trim())p.Main.Nickname=p.PlayerName.trim(); debounceRender()};
   $$("tbody tr",card).forEach((tr,i)=>$$("input,select",tr).forEach(el=>{el.onchange=()=>{let c=p[tr.dataset.k],f=el.dataset.f;c[f]=f==="Namtool"?(fmtNam(el.value)?parseInt(el.value):null):el.value;if(f==="Server"&&i===0){["Sub1","Sub2","Sub3","Sub4"].forEach(k=>{if(!p[k+"ServerOverride"])p[k].Server=c.Server})}if(f==="Server"&&i>0)p[tr.dataset.k+"ServerOverride"]=c.Server!==p.Main.Server;validateNicknames();render()}}))
 });
 renderMerc("#m1",0);renderMerc("#m2",5);wireGridSelection();
}
function renderMerc(sel,start){let root=$(sel);root.innerHTML=`<table><thead><tr><th>본캐</th><th>닉네임</th><th>서버명</th><th>직업</th><th>남툴</th></tr></thead><tbody>${state.Mercenaries.slice(start,start+5).map((m,i)=>`<tr data-i="${start+i}"><td>${inputCell(m.MainNickname,'data-f="MainNickname"')}</td><td>${inputCell(m.Nickname,'data-f="Nickname"')}</td><td>${inputCell(m.Server,'data-f="Server"')}</td><td>${jobSelect(m.Job,'data-f="Job"')}</td><td>${inputCell(fmtNam(m.Namtool),'data-f="Namtool"')}</td></tr>`).join("")}</tbody></table>`;$$("tr[data-i]",root).forEach(tr=>$$("input,select",tr).forEach(el=>el.onchange=()=>{let m=state.Mercenaries[+tr.dataset.i],f=el.dataset.f;m[f]=f==="Namtool"?(fmtNam(el.value)?parseInt(el.value):null):el.value;validateNicknames();render()}))}
function validateNicknames(){let seen=new Set();for(const p of state.PlayerGroups)for(const c of chars(p)){let n=c.Nickname.trim().toLowerCase();if(n&&seen.has(n)){alert("중복된 닉네임입니다.");return false}if(n)seen.add(n)}for(const m of state.Mercenaries){let n=m.Nickname.trim().toLowerCase();if(n&&seen.has(n)){alert("중복된 닉네임입니다.");return false}if(n)seen.add(n)}return true}
let deb;function debounceRender(){clearTimeout(deb);deb=setTimeout(()=>render(),300)}
function wireGridSelection(){$$("td input,td select").forEach(el=>el.addEventListener("focus",()=>{let td=el.closest("td");$$("td.selected-cell").forEach(x=>x.classList.remove("selected-cell"));td.classList.add("selected-cell")}))}

function renderRound(round){normalizeRound(round);let app=$("#app"); if(mechanicView){renderMechanics(round);return}
 app.innerHTML=`<div class="section-title">파티 편성</div><div class="round-toolbar"><button id="go" class="mechanic-btn" ${complete(round)?"":"disabled"}>기믹 수행</button><button id="copy">편성 닉네임 복사</button></div><div class="formation" id="formation"></div>`;
 $("#go").onclick=()=>{mechanicView=true;render()};$("#copy").onclick=()=>previewCopy(round);let root=$("#formation");root.append(partyTable(round,0,"1파티"));root.append(partyTable(round,5,"2파티"));wireFormation(round)
}
function opt(items,value,label=x=>x.name){return `<option value=""></option>${items.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(value)?"selected":""}>${esc(label(x))}</option>`).join("")}`}
function partyTable(round,start,title){let r=state.Rounds[round],box=document.createElement("div");box.className="party-box";box.innerHTML=`<div class="party-title">${title}</div><table><thead><tr><th>플레이어</th><th>직업</th><th>캐릭터</th><th>2넴<br>변경</th><th>직업</th><th>캐릭터</th></tr></thead><tbody></tbody></table>`;let body=$("tbody",box);
 for(let i=start;i<start+5;i++){let id=r.PartyPlayerIds[i],av=available(id,round),base=av.find(c=>c.CharacterId===r.PartyCharacterIds[i]),forced=base&&forceSwap(id,round,base.CharacterId);let baseJobs=[...new Map(av.filter(c=>c.Job).map(c=>[c.Type+"|"+c.Job,{id:c.Type+"|"+c.Job,name:`[${c.Type==="main"?"본":"부"}] ${c.Job}`}])).values()],bk=base?base.Type+"|"+base.Job:"";let baseChars=base?av.filter(c=>c.Type===base.Type&&c.Job===base.Job):[];
   let swaps=av.filter(c=>!base||c.CharacterId!==base.CharacterId),sw=swaps.find(c=>c.CharacterId===r.PartySwapCharacterIds[i]),swapJobs=[...new Map(swaps.filter(c=>c.Job).map(c=>[c.Type+"|"+c.Job,{id:c.Type+"|"+c.Job,name:`[${c.Type==="main"?"본":"부"}] ${c.Job}`}])).values()],sk=sw?sw.Type+"|"+sw.Job:"",swapChars=sw?swaps.filter(c=>c.Type===sw.Type&&c.Job===sw.Job):[];
   let tr=document.createElement("tr");tr.dataset.i=i;tr.innerHTML=`<td><select data-role="player">${opt(playerChoices(),id)}</select></td><td><select data-role="job">${opt(baseJobs,bk)}</select></td><td><select data-role="char">${opt(baseChars,r.PartyCharacterIds[i],formDisplay)}</select></td><td><select data-role="mode" class="${forced?"forced":""}">${forced?`<option selected>교체</option>`:`<option ${r.PartySwapModes[i]==="고정"?"selected":""}>고정</option><option ${r.PartySwapModes[i]==="교체"?"selected":""}>교체</option>`}</select></td><td><select data-role="swapjob" ${r.PartySwapModes[i]==="교체"?"":"disabled"}>${opt(swapJobs,sk)}</select></td><td><select data-role="swap" ${r.PartySwapModes[i]==="교체"?"":"disabled"}>${opt(swapChars,r.PartySwapCharacterIds[i],formDisplay)}</select></td>`;body.appendChild(tr)}
 return box
}
function wireFormation(round){let r=state.Rounds[round];$$(".formation select").forEach(s=>{let i=+s.closest("tr").dataset.i,role=s.dataset.role,key=`${i}:${role}`;if(selectedFormation.has(key))s.classList.add("selected-cell");s.onmousedown=()=>{selectedFormation.clear();selectedFormation.add(key);applySel()};s.onchange=()=>{let id=r.PartyPlayerIds[i],av=available(id,round);if(role==="player"){r.PartyPlayerIds[i]=+s.value||0;r.PartyCharacterIds[i]="";r.PartySwapModes[i]="고정";r.PartySwapCharacterIds[i]=""}else if(role==="job"){let [t,j]=s.value.split("|");let c=available(id,round).filter(c=>c.Type===t&&c.Job===j);r.PartyCharacterIds[i]=c.length===1?c[0].CharacterId:"";r.PartySwapCharacterIds[i]=""}else if(role==="char"){r.PartyCharacterIds[i]=s.value;r.PartySwapCharacterIds[i]=""}else if(role==="mode"){r.PartySwapModes[i]=s.value;r.PartySwapCharacterIds[i]=""}else if(role==="swapjob"){let [t,j]=s.value.split("|");let c=av.filter(c=>c.CharacterId!==r.PartyCharacterIds[i]&&c.Type===t&&c.Job===j);r.PartySwapCharacterIds[i]=c.length===1?c[0].CharacterId:""}else if(role==="swap")r.PartySwapCharacterIds[i]=s.value;for(let rr=round;rr<5;rr++)normalizeRound(rr);render()}})}
function applySel(){$$(".formation select").forEach(s=>{let k=`${s.closest("tr").dataset.i}:${s.dataset.role}`;s.classList.toggle("selected-cell",selectedFormation.has(k))})}
document.addEventListener("keydown",e=>{if(page===0||mechanicView)return;if(e.ctrlKey&&e.key.toLowerCase()==="a"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();selectedFormation.clear();$$(".formation select").forEach(s=>selectedFormation.add(`${s.closest("tr").dataset.i}:${s.dataset.role}`));applySel()}else if(e.key==="Escape"){selectedFormation.clear();applySel()}else if(e.key==="Delete"&&selectedFormation.size){let round=page-1,r=state.Rounds[round];for(const k of selectedFormation){let [is,role]=k.split(":"),i=+is;if(role==="player"){r.PartyPlayerIds[i]=0;r.PartyCharacterIds[i]="";r.PartySwapModes[i]="고정";r.PartySwapCharacterIds[i]=""}else if(role==="job"||role==="char"){r.PartyCharacterIds[i]="";r.PartySwapCharacterIds[i]=""}else if(role==="mode"){if(!forceSwap(r.PartyPlayerIds[i],round,r.PartyCharacterIds[i]))r.PartySwapModes[i]="고정";r.PartySwapCharacterIds[i]=""}else r.PartySwapCharacterIds[i]=""}selectedFormation.clear();render()}})

function mechanicChoices(round,party=0){let r=state.Rounds[round],a=[];for(let i=0;i<10;i++){if(party&&((i<5?1:2)!==party))continue;let c=effective(r,i,true);if(c)a.push({id:`${c.PlayerId}:${c.CharacterId}`,c,party:i<5?1:2})}return a}
function renderMechanics(round){let r=state.Rounds[round],app=$("#app");app.innerHTML=`<div class="mechanics"><button class="backlink">← 역할 입력 완료 후 편성표로 돌아가세요.</button><div class="section-title">드리블</div><div class="dribble-wrap"><div class="dribble p1" id="d1"></div><div class="dribble p2" id="d2"></div></div><div class="section-title">신호등 · 각 위치에서 닉네임 선택</div><div class="signal-area"><div class="circle"></div><div id="signals"></div></div><div class="role-box"><div class="section-title">헤드조</div><div class="role-grid" id="head"></div></div><div class="role-box"><div class="section-title">빽조</div><div class="role-grid" id="back"></div></div></div>`;
 $(".backlink").onclick=()=>{mechanicView=false;render()};renderDribble(round,0,"#d1","1파티",D1P1);renderDribble(round,5,"#d2","2파티",D1P2);renderSignals(round);renderRoles(round)
}
function renderDribble(round,start,sel,title,roles){let root=$(sel);root.innerHTML=`<b>${title} / 드리블</b><table><tr><th>닉네임[서버명] 직업</th><th>드리블</th></tr>${Array.from({length:5},(_,x)=>{let i=start+x,c=effective(state.Rounds[round],i,false);return `<tr><td>${esc(mechDisplay(c))}</td><td><select data-i="${i}">${roles.map(v=>`<option ${state.Rounds[round].D1Roles[i]===v?"selected":""}>${esc(v)}</option>`).join("")}</select></td></tr>`}).join("")}</table>`;$$("select",root).forEach(s=>s.onchange=()=>state.Rounds[round].D1Roles[+s.dataset.i]=s.value)}
function uniqueOptions(round,current,values,party=0){let used=new Set(values.filter((x,i)=>i!==current&&x));return mechanicChoices(round,party).filter(x=>!used.has(x.id))}
function renderSignals(round){let root=$("#signals"),r=state.Rounds[round],pos=[[700,80],[502,162],[420,360],[502,558],[700,640],[898,558],[980,360],[898,162]];root.innerHTML="";for(let i=0;i<8;i++){let wrap=document.createElement("div");wrap.className="signal";wrap.style.left=pos[i][0]+"px";wrap.style.top=pos[i][1]+"px";let opts=uniqueOptions(round,i,r.Signals);wrap.innerHTML=`<select data-i="${i}"><option value="">${POINTS[i]}</option>${opts.map(x=>`<option value="${x.id}" ${r.Signals[i]===x.id?"selected":""}>${esc(mechDisplay(x.c))}</option>`).join("")}</select>`;root.appendChild(wrap)}$$("select",root).forEach(s=>s.onchange=()=>{r.Signals[+s.dataset.i]=s.value;renderSignals(round)})}
function renderRoles(round){let r=state.Rounds[round],head=$("#head");let labels=["별징","1번","2번","3번","4번","5번"];head.innerHTML=labels.map((l,i)=>`<label>${l}<select data-i="${i}"><option></option>${uniqueOptions(round,i,r.Mercy,1).map(x=>`<option value="${x.id}" ${r.Mercy[i]===x.id?"selected":""}>${esc(mechDisplay(x.c))}</option>`).join("")}</select></label>`).join("");$$("select",head).forEach(s=>s.onchange=()=>{r.Mercy[+s.dataset.i]=s.value;renderRoles(round)});
 let back=$("#back");back.innerHTML=`<label>해골징<select><option></option>${mechanicChoices(round,2).map(x=>`<option value="${x.id}" ${r.BackSkull===x.id?"selected":""}>${esc(mechDisplay(x.c))}</option>`).join("")}</select></label>`;$("select",back).onchange=e=>r.BackSkull=e.target.value
}
function shortJob(j){return (j||"").endsWith("성")?j.slice(0,-1):(j||"")}
function copyLine(c,mech="",replaced=false){if(!c)return "";let a=[(replaced?"(교체)":"")+full(c),shortJob(c.Job)];if(!c.Mercenary)a.push(c.Type==="main"?"본":"부");if(mech)a.push(mech);return a.filter(Boolean).join(" ")}
function signalTime(round,c){if(!c)return "";let id=`${c.PlayerId}:${c.CharacterId}`,idx=state.Rounds[round].Signals.indexOf(id);return idx>=0?POINTS[idx]:""}
function buildCopy(round){let r=state.Rounds[round],a=["1넴",""];for(let p=0;p<2;p++){for(let i=p*5;i<p*5+5;i++){let c=effective(r,i,false),x=copyLine(c,r.D1Roles[i]);if(x)a.push(x)}if(p===0)a.push("")}a.push("","2넴","");for(let p=0;p<2;p++){for(let i=p*5;i<p*5+5;i++){let b=effective(r,i,false),c=effective(r,i,true),rep=r.PartySwapModes[i]==="교체"&&b&&c&&b.CharacterId!==c.CharacterId;let x=copyLine(c,signalTime(round,c),rep);if(x)a.push(x)}if(p===0)a.push("")}let heads=["헤드(자비)조"],labs=["별징","1번칸","2번칸","3번칸","4번칸","5번칸"];r.Mercy.slice(0,6).forEach((id,i)=>{let x=mechanicChoices(round,1).find(v=>v.id===id);if(x)heads.push(labs[i]+" "+full(x.c))});a.push("",heads.join(" - "));let b=mechanicChoices(round,2).find(v=>v.id===r.BackSkull);a.push(b?"빽조 - "+full(b.c):"빽조");return a.join("\n")}
function previewCopy(round){if(!state.Rounds[round].PartyCharacterIds.some(Boolean)){alert("복사할 편성 정보가 없습니다.");return}$("#copyText").value=buildCopy(round);$("#copyDialog").showModal()}
$("#copyCancel").onclick=()=>$("#copyDialog").close();$("#copyConfirm").onclick=async()=>{try{await navigator.clipboard.writeText($("#copyText").value)}catch{$("#copyText").select();document.execCommand("copy")}$("#copyDialog").close();alert("편성 닉네임을 복사했습니다.")}
$("#saveBtn").onclick=()=>{state.SavedAt=new Date().toISOString();let blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`편성표_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
$("#loadFile").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{let x=JSON.parse(await f.text());if(!x||!Array.isArray(x.Rounds)||x.Rounds.length!==5)throw 0;state=x;state.PlayerGroups=state.PlayerGroups||[];state.Mercenaries=state.Mercenaries||[];while(state.Mercenaries.length<10)state.Mercenaries.push({Id:1001+state.Mercenaries.length,MainNickname:"",Nickname:"",Server:"",Job:"",Namtool:null});for(let i=0;i<5;i++){state.Rounds[i].PartySwapModes=state.Rounds[i].PartySwapModes||Array(10).fill("고정");state.Rounds[i].D1Roles=state.Rounds[i].D1Roles||Array(10).fill("");state.Rounds[i].Signals=(state.Rounds[i].Signals||Array(8).fill("")).map(x=>typeof x==="string"&&x.includes(":")?x:"");state.Rounds[i].Mercy=(state.Rounds[i].Mercy||Array(10).fill("")).map(x=>typeof x==="string"&&x.includes(":")?x:"");state.Rounds[i].BackSkull=typeof state.Rounds[i].BackSkull==="string"&&state.Rounds[i].BackSkull.includes(":")?state.Rounds[i].BackSkull:""}render();alert("불러왔습니다.")}catch{alert("올바른 편성표 저장 파일이 아닙니다.")}e.target.value=""}
render();